# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-Ex-Dialogs
version:      0.09
version_from: lib/Gtk2/Ex/Dialogs.pm
installdirs:  site
requires:
    Gnome2::VFS:                   1.003
    Gtk2:                          1.04
    Gtk2::Ex::Utils:               0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
